# // Author: Fu Wenbo
# // SPDX-FileCopyrightText: 2026 Fu Wenbo
# // SPDX-License-Identifier: AGPL-3.0-or-later

# Windows counterpart of prepare_adi_lib.sh.
#
# The ADI HDL library ships packaging scripts but no packaged IP: every
# library/<ip>/component.xml is generated by running <ip>_ip.tcl in Vivado.
# On Linux that is done by "make" inside adi-hdl/library. There is no make on
# a stock Windows Vivado install, so this script packages the IPs that the
# OpenWiFi block designs instantiate, one Vivado batch run each.
#
# Usage, from the repository root:
#
#   git submodule update --init adi-hdl
#   .\prepare_adi_lib.ps1 -Vivado 'C:\Xilinx\Vivado\2020.2\bin\vivado.bat'
#
# Vivado 2020.2 is older than the version ADI declares support for, so the
# ADI version check is downgraded to a warning. That is the same escape hatch
# ADI documents via ADI_IGNORE_VERSION_CHECK.

param(
    [Parameter(Mandatory = $true)] [string] $Vivado,
    [string[]] $Ip = @(
        'axi_ad9361',
        'util_pack/util_cpack2',
        'util_pack/util_upack2',
        'util_wfifo',
        'util_rfifo',
        'util_tdd_sync',
        'xilinx/util_clkdiv'
    ),
    [switch] $Force
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$library = Join-Path $repoRoot 'adi-hdl\library'

if (-not (Test-Path (Join-Path $library 'axi_ad9361\axi_ad9361_ip.tcl'))) {
    throw "adi-hdl submodule is not populated. Run: git submodule update --init adi-hdl"
}
if (-not (Test-Path $Vivado)) {
    throw "Vivado not found at $Vivado"
}

$env:ADI_IGNORE_VERSION_CHECK = '1'

$failed = @()
foreach ($relative in $Ip) {
    $name = Split-Path ($relative -replace '/', '\') -Leaf
    $directory = Join-Path $library ($relative -replace '/', '\')
    $component = Join-Path $directory 'component.xml'

    if (-not (Test-Path $directory)) { throw "No such ADI IP directory: $directory" }
    if ((Test-Path $component) -and -not $Force) {
        Write-Host "skip  $relative (already packaged)"
        continue
    }

    Write-Host "build $relative"
    Push-Location $directory
    try {
        & $Vivado -mode batch -source "${name}_ip.tcl" -nojournal -log "package_${name}.log" | Out-Null
        if (-not (Test-Path $component)) {
            $failed += $relative
            Write-Warning "$relative did not produce component.xml; see $directory\package_${name}.log"
        }
    } finally {
        Pop-Location
    }
}

if ($failed.Count -gt 0) {
    throw "Failed to package: $($failed -join ', ')"
}
Write-Host "ADI IP packaging complete."
